on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '3*'

name: create_release

jobs:
  build:
    name: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Slack Notification on Start
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RELEASE }}
          SLACK_CHANNEL: notify-nc3-release
          SLACK_TITLE: "${{ github.repository }}"
          SLACK_COLOR: "#f0ad4e"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            NetCommons ${{ github.ref }} released.
          draft: false
          prerelease: false

      - name: Slack Notification on Finish
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RELEASE }}
          SLACK_CHANNEL: notify-nc3-release
          SLACK_TITLE: "${{ github.repository }}"
          SLACK_COLOR: good
