on: [ push, pull_request ]

name: test

jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: [ '7.2' ]

    env:
        NC3_BUILD_DIR: "/opt/nc3"
        NC3_GIT_URL: "git://github.com/NetCommons3/NetCommons3"
        NC3_GIT_BRANCH: "master"
        PLUGIN_BUILD_DIR: ${{ github.workspace }}
        PHP_VERSION: ${{ matrix.php }}
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cakephp_test
        COMPOSE_INTERACTIVE_NO_CLI: 1

    steps:
      - name: docker-compose install
        shell: bash
        run: |
          curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
          docker-compose --version

      - name: wget docker-compose.yml
        uses: wei/wget@v1
        with:
          args: https://gist.githubusercontent.com/s-nakajima/b1b961174b136afe55500c0e8cfbf741/raw/4aeeebb69e3b7ffaf3ac786e33ef0dbfb8b8139a/docker-compose.yml

      - name: environment variable
        shell: bash
        run: |
          echo ${GITHUB_WORKSPACE}
          echo ${PLUGIN_BUILD_DIR}
          echo ${PHP_VERSION}

      - run: docker-compose rm -a -f

      - run: docker-compose up -d

      - run: |
          docker-compose start
          docker ps
          docker-compose ps

      - run: docker-compose exec -T nc3app touch /opt/test

      - run: docker-compose exec -T nc3app ls -l /opt/

      - run: docker-compose exec -T nc3app bash /opt/scripts/start-on-docker.sh

#      - name: nc3app docker started
#        shell: bash
#        run: |
#          docker-compose exec nc3app bash /opt/scripts/start-on-docker.sh

#      - name: nc3app app build
#        shell: bash
#        run: |
#          docker-compose exec nc3app bash /opt/scripts/app-build.sh
#
#      - name: phpcs
#        shell: bash
#        run: |
#          docker-compose exec nc3app bash /opt/scripts/phpcs.sh
#
#      - name: phpmd
#        shell: bash
#        run: |
#          docker-compose exec nc3app bash /opt/scripts/phpmd.sh
#
#      - name: phpcpd
#        shell: bash
#        run: |
#          docker-compose exec nc3app bash /opt/scripts/phpcpd.sh
#
#      - name: gjslint
#        shell: bash
#        run: |
#          docker-compose exec nc3app bash /opt/scripts/gjslint.sh
#
#      - name: phpdoc
#        shell: bash
#        run: |
#          docker-compose exec nc3app bash /opt/scripts/phpdoc.sh
#
#      - name: phpunit
#        shell: bash
#        run: |
#          docker-compose exec nc3app bash /opt/scripts/phpunit.sh
#
      - run: docker-compose rm -a -f
