on: [ push, pull_request ]

name: test

jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: [ '7.2' ]

    env:
        NC3_BUILD_DIR: "/opt/nc3"
        NC3_GIT_URL: "git://github.com/NetCommons3/NetCommons3"
        NC3_GIT_BRANCH: "master"
        PLUGIN_BUILD_DIR: ${{ github.workspace }}
        PHP_VERSION: ${{ matrix.php }}
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cakephp_test
        COMPOSE_INTERACTIVE_NO_CLI: 1

    steps:
      - uses: actions/checkout@v2

      - name: environment
        run: |
          echo ${GITHUB_WORKSPACE}
          echo ${PLUGIN_BUILD_DIR}
          echo ${PHP_VERSION}
          ls -al ${PLUGIN_BUILD_DIR}

      - name: docker-compose install
        run: |
          curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
          docker-compose --version

      - name: wget docker-compose.yml
        uses: wei/wget@v1
        with:
          args: https://gist.githubusercontent.com/s-nakajima/b1b961174b136afe55500c0e8cfbf741/raw/76542726f13a9d3f3dfcd62e4333b5d42e3ac03f/docker-compose.yml

      - name: docker-compose start
        run: |
          docker-compose up -d
          docker-compose start

      - run: docker ps

      - name: docker starting check
        run: docker-compose exec -T nc3app bash /opt/scripts/start-on-docker.sh

      - name: nc3 build
        run: docker-compose exec -T nc3app bash /opt/scripts/app-build.sh

      - name: phpcs (PHP CodeSniffer)
        run: docker-compose exec -T nc3app bash /opt/scripts/phpcs.sh

      - name: phpmd (PHP Mess Detector)
        run: docker-compose exec -T nc3app bash /opt/scripts/phpmd.sh

      - name: phpcpd (PHP Copy/Paste Detector)
        run: docker-compose exec -T nc3app bash /opt/scripts/phpcpd.sh

      - name: gjslint (JavaScript Style Check)
        run: docker-compose exec -T nc3app bash /opt/scripts/gjslint.sh

      - name: phpdoc (PHP Documentor)
        run: docker-compose exec -T nc3app bash /opt/scripts/phpdoc.sh

      - name: phpunit (PHP UnitTest)
        run: docker-compose exec -T nc3app bash /opt/scripts/phpunit.sh

      - run: docker-compose rm -f
