on: [ push, pull_request ]

name: tests

jobs:
  tests:
    name: tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: [ '7.2' ]

    env:
        NC3_BUILD_DIR: "/opt/nc3"
        NC3_GIT_URL: "git://github.com/NetCommons3/NetCommons3"
        NC3_GIT_BRANCH: "master"
        PLUGIN_BUILD_DIR: ${{ github.workspace }}
        PHP_VERSION: ${{ matrix.php }}
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cakephp_test
        COMPOSE_INTERACTIVE_NO_CLI: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: environment
        run: |
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          echo "PLUGIN_BUILD_DIR=${PLUGIN_BUILD_DIR}"
          echo "PHP_VERSION=${PHP_VERSION}"
          echo "COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}"
          ls -al ${PLUGIN_BUILD_DIR}
          mkdir -p /opt/coveralls

      - name: docker-compose install
        run: |
          curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
          docker-compose --version

      - name: wget docker-compose.yml
        uses: wei/wget@v1
        with:
          args: https://raw.githubusercontent.com/NetCommons3/nc3app-docker/main/docker-compose.yml

      - name: docker-compose start
        run: |
          docker-compose up -d
          docker-compose start

      - run: docker ps

      - name: check libraries
        run: docker-compose exec -T nc3app bash /opt/scripts/start-on-docker.sh

      - name: nc3 build
        run: docker-compose exec -T nc3app bash /opt/scripts/app-build.sh

      - name: phpcs (PHP CodeSniffer)
        run: docker-compose exec -T nc3app bash /opt/scripts/phpcs.sh

      - name: phpmd (PHP Mess Detector)
        run: docker-compose exec -T nc3app bash /opt/scripts/phpmd.sh

      - name: phpcpd (PHP Copy/Paste Detector)
        run: docker-compose exec -T nc3app bash /opt/scripts/phpcpd.sh

      - name: gjslint (JavaScript Style Check)
        run: docker-compose exec -T nc3app bash /opt/scripts/gjslint.sh

      - name: phpdoc (PHP Documentor)
        run: docker-compose exec -T nc3app bash /opt/scripts/phpdoc.sh

      - name: phpunit (PHP UnitTest)
        run: |
          docker-compose exec -T nc3app bash /opt/scripts/phpunit.sh
          #docker-compose exec -T nc3app ls -al ${NC3_BUILD_DIR}/build/logs/

      - run: |
          #docker-compose exec -T nc3app cp -pf ${NC3_BUILD_DIR}/build/logs/* /opt/coveralls/
          docker-compose exec -T nc3app bash /opt/scripts/coveralls.sh
          ls -l /opt/coveralls

      - name: push coveralls
        run: |
          composer global require php-coveralls/php-coveralls
          ls -al ~/
          ls -al ~/.composer/vendor/bin/
          ls -al ~/.config/composer/vendor/bin/

      #- name: push coveralls
      #  uses: coverallsapp/github-action@master
      #  with:
      #    github-token: ${{ secrets.GH_TOKEN }}
      #    flag-name: ${{ matrix.php }}
      #    path-to-lcov: /opt/coveralls/clover.cov

      - run: docker-compose rm -f
